module.exports = {
    "AUTHENTICATED": "",
    "PASSWORD_SUCCESSFULLY_CHANGED": "",
    "WRONG_SERVER": "",
    "WRONG_PASSWORD": "",
    "WRONG_PASSWORD_LENGTH": "",
    "WRONG_PASSWORD_CONFIRMATION": "",
    "WRONG_PASSWORD_EQUALS": "",
    "WRONG_USERNAME": "",
    "WRONG_USERNAME_NOT_ALPHA": "",
    "WRONG_EMAIL": "",
    "USER_ALREADY_EXIST": "",
    "USER_DOES_NOT_EXIST": "",
    "ERROR_IN_DATABASE": "",
    "REGISTER_SUCCESSFULL": "",
    "REGISTRATION_MESSAGE": "",
    "REGISTRATION_BUTTON_DESCRIPTION":"Vérifier mon compte",
    "REGISTRATION_BUTTON_TITLE": "",
    "REGISTRATION_EMAIL_ERROR": "Une erreur est survenue en voulant vous envoyer un mail",
    "REGISTRATION_EMAIL_SENDER": "Inscription NosWings",
    "REGISTRATION_GREETINGS": "Salutations",
    "REGISTRATION_EMAIL_SUBJECT": "NosWings - Inscription",
    "REGISTRATION_FOOTER_DESCRIPTION": "",
    "TITLE_DASHBOARD": "Accueil",
    "TITLE_REGISTER": "Inscription",
    "TITLE_USER_MANAGEMENT": "Gestion de compte",
    "TITLE_SHOP_CATEGORY_PET": "Nosmall - Pets",
    "TITLE_SHOP": "Nosmall",
    "TITLE_CART": "",
    "TITLE_LOGIN": "Interface de connexion",
    "STAFF_NAME": "L'équipe NosWings",
};