module.exports = {
    "AUTHENTICATED": "",
    "PASSWORD_SUCCESSFULLY_CHANGED": "",
    "WRONG_SERVER": "",
    "WRONG_PASSWORD": "",
    "WRONG_PASSWORD_LENGTH": "",
    "WRONG_PASSWORD_CONFIRMATION": "",
    "WRONG_PASSWORD_EQUALS": "Mots de passes non similaires",
    "WRONG_USERNAME": "",
    "WRONG_USERNAME_NOT_ALPHA": "Votre identifiant doit contenir seulement des lettres et des chiffres",
    "WRONG_EMAIL": "Mauvais mail",
    "USER_ALREADY_EXIST": "L'identifiant existe déjà dans notre base de données",
    "USER_DOES_NOT_EXIST": "",
    "ACCOUNT_ALREADY_VALIDATED": "Votre compte a déjà été validé",
    "ERROR_IN_DATABASE": "Erreur dans la base de données",
    "REGISTER_SUCCESSFULL": "Votre inscription s'est déroulée avec succès, vous allez recevoir un mail de validation",
    "REGISTRATION_MESSAGE": "",
    "REGISTRATION_BUTTON_DESCRIPTION":"Cliquez sur le bouton afin de vérifier votre compte",
    "REGISTRATION_BUTTON_TITLE": "Vérifier mon compte",
    "REGISTRATION_EMAIL_ERROR": "Une erreur est survenue en voulant vous envoyer un mail",
    "REGISTRATION_EMAIL_SENDER": "Inscription NosWings",
    "REGISTRATION_GREETINGS": "Salutations",
    "REGISTRATION_EMAIL_SUBJECT": "NosWings - Inscription",
    "REGISTRATION_FOOTER_DESCRIPTION": "",
    "TITLE_DASHBOARD": "Accueil",
    "TITLE_REGISTER": "Inscription",
    "TITLE_USER_MANAGEMENT": "Gestion de compte",
    "TITLE_SHOP_CATEGORY_PET": "Nosmall - Pets",
    "TITLE_SHOP": "Nosmall",
    "TITLE_CART": "",
    "TITLE_LOGIN": "Interface de connexion",
    "STAFF_NAME": "L'équipe NosWings",
};
